services:
  postgres:
    image: postgres:16-alpine
    container_name: bankofgraeme-db
    environment:
      POSTGRES_DB: bankofgraeme
      POSTGRES_USER: bankadmin
      POSTGRES_PASSWORD: BankDev123!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: bankofgraeme-azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

volumes:
  pgdata:
